spring:
  application:
    name: msp-auth
  profiles:
    active: prop1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.11.12:1111/eureka, http://192.168.11.13:1111/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true