spring:
  application:
    name: msp-ftp
  profiles:
    active: prop1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.11.12:1111/eureka, http://192.168.11.13:1113/eureka