# 指定生效的配置
spring:
  profiles:
    active: prop1
  application:
    name: msp-center
# eureka配置
eureka:
  client:
    register-with-eureka: true # 是否注册到eureka 服务
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.11.12:1111/eureka, http://192.168.11.13:1112/eureka
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    #    扫描失效服务的时间
    eviction-interval-timer-in-ms: 1000
    peer-node-read-timeout-ms: 3000
    peer-node-connect-timeout-ms: 1000
  instance:
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true