spring:
  profiles:
    active: prop1
  application:
    name: msp-center
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://fcstudev.com:8080/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 30000
    peer-node-read-timeout-ms: 3000
    peer-node-connect-timeout-ms: 1000