spring:
  application:
    name: msp-mail
  profiles:
    active: prop1
  rabbitmq:
    host: 192.168.1.103
    port: 5672
    username: rabbit
    password: rabbit
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/MSPDB?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: mspuser
    password: MyPass@123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000           # 等待连接池分配连接的最大时长
      minimum-idle: 5                     # 最小连接数
      maximum-pool-size: 20               # 最大连接数
      auto-commit: true                   # 自动提交
      idle-timeout: 600000                # 默认10分钟
      max-lifetime: 1800000               # 连接的生命时长，超时且没有被使用则被释放，默认：30分钟
      pool-name: DataSourceHikariCP       # 连接池名称
      connection-test-query: SELECT 1
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: 192.168.1.103
    # redis端口（默认为6379）
    port: 16379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.103:11111/eureka, http://192.168.1.103:21111/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true