spring:
  application:
    name: msp-mail
  profiles:
    active: prop1
  datasource:
    url: jdbc:mysql:///MSPDB?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: 
    password:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000           # 等待连接池分配连接的最大时长
      minimum-idle: 5                     # 最小连接数
      maximum-pool-size: 20               # 最大连接数
      auto-commit: true                   # 自动提交
      idle-timeout: 600000                # 默认10分钟
      max-lifetime: 1800000               # 连接的生命时长，超时且没有被使用则被释放，默认：30分钟
      pool-name: DataSourceHikariCP       # 连接池名称
      connection-test-query: SELECT 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://:1111/eureka, http://:1112/eureka

