spring:
  application:
    name: msp-mock-service
server:
  port: 9090 #对外http服务端口
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.103:11111/eureka, http://192.168.1.103:21111/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
