spring:
  application:
    name: msp-alert
  profiles:
    active: prop1
  rabbitmq:
    host: 192.168.11.20
    port: 5672
    username: rabbit
    password: rabbit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://111.229.237.232:1111/eureka, http://111.229.237.232:1112/eureka
